name = input("Give a name")
verb = input("Give a verb")
name2 = input("Give a name")
adjective = input("Give a adjective")
verb2 = input("Give a verb")
place = input("Give a place")
fruit = input("Give a fruit")
color = input("Give a color")
weapon = input("Name a weapon")
place2 = input("Give a place")

print("There was a boy named %s" % name)
print("He was %s all day and all night" % verb)
print("The friend %s was with him" % name2)
print("They were both %s" % adjective)
print("They had a good time but then they %s all day again" % verb2)
print("They did this all the way till they got to %s" % place)
print("They grabbed a %s" % fruit)
print("The fruit had a %s tone" % color)
print("The fruit came alive and had a %s" % weapon)
print("They ran all the way to %s so they can escape from the fruit" % place2)